alpaca_trading_base_url = 'https://paper-api.alpaca.markets'
alpaca_live_trading_base_url = 'https://api.alpaca.markets'
alpaca_data_base_url = 'https://data.alpaca.markets'
alpaca_api_key_id = 'PK51GT0T6O7H7KCIF4CU'
alpaca_api_secret = 'fDuOvlcChSKsgfjtm1H8PN9R5jpAibBaJeGZoG2S'
alpha_vantage_api_key = 'BL6DGN9RIVKMEYRA'